CREATE TABLE [dbo].[Audit]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
    [OrganisationId] UNIQUEIDENTIFIER NOT NULL, 
    [UpdatedBy] NVARCHAR(30) NOT NULL, 
    [UpdatedAt] DATETIME2 NOT NULL, 
    [AuditData] NVARCHAR(MAX) NOT NULL
)
